[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.deploymentStrategy]
type = "recreate"  # 使用 recreate 策略（先停后启）
# type = "rolling"  # 默认值，滚动更新